// Locations Seed Data
// 23 India treatment locations + 10 US follow-up locations

export interface ClinicSeedData {
  name: string
  address: string
  phone: string
  specialties: string[]
  rating: number
  reviewCount: number
}

export interface NearbyStay {
  name: string
  distance: string
}

export interface IndiaLocationSeedData {
  id: string
  city: string
  state: string
  country: 'India'
  type: 'treatment'
  tagline: string
  description: string
  clinics: ClinicSeedData[]
  doctors: number
  facilities: string[]
  nearbyStays: NearbyStay[]
  fromAirport: string
  coordinates: { lat: number; lng: number }
  featured: boolean
  opensInNewTab: boolean
}

export interface USLocationSeedData {
  id: string
  city: string
  state: string
  stateCode: string
  country: 'USA'
  type: 'followup'
  tagline: string
  description: string
  services: string[]
  guarantee: string
  emergencyLine: string
  coordinates: { lat: number; lng: number }
  featured: boolean
  opensInNewTab: boolean
}

export const indiaLocationsData: IndiaLocationSeedData[] = [
  {
    id: 'hyderabad',
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    type: 'treatment',
    tagline: 'Premier dental care in the City of Pearls',
    description: 'Our flagship Hyderabad center offers world-class dental care with state-of-the-art facilities and renowned specialists.',
    clinics: [
      {
        name: 'Atidi Dental Care - Jubilee Hills',
        address: 'Jubilee Hills, Hyderabad 500033',
        phone: '+91 40 XXXX XXXX',
        specialties: ['Implants', 'Cosmetic', 'Full Mouth'],
        rating: 4.9,
        reviewCount: 680,
      },
      {
        name: 'Atidi Dental Care - Banjara Hills',
        address: 'Banjara Hills, Hyderabad 500034',
        phone: '+91 40 XXXX XXXX',
        specialties: ['Root Canal', 'Orthodontics', 'Laser Dentistry'],
        rating: 4.9,
        reviewCount: 520,
      },
    ],
    doctors: 35,
    facilities: [
      'Digital X-ray & 3D CT Scan',
      'CAD/CAM same-day crowns',
      'In-house dental lab',
      'VIP recovery suites',
      'Airport pickup available',
    ],
    nearbyStays: [
      { name: 'Taj Falaknuma Palace', distance: '20 min' },
      { name: 'ITC Kohenur', distance: '10 min' },
      { name: 'Park Hyatt', distance: '15 min' },
    ],
    fromAirport: '35 min from Rajiv Gandhi International Airport',
    coordinates: { lat: 17.3850, lng: 78.4867 },
    featured: true,
    opensInNewTab: true,
  },
  {
    id: 'bangalore',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    type: 'treatment',
    tagline: 'Advanced dental technology in India\'s tech hub',
    description: 'Our Bangalore center combines cutting-edge dental technology with the city\'s comfortable climate and excellent hospitality.',
    clinics: [
      {
        name: 'Atidi Dental Care - Indiranagar',
        address: 'Indiranagar, Bangalore 560038',
        phone: '+91 80 XXXX XXXX',
        specialties: ['Implants', 'Cosmetic', 'Laser Dentistry'],
        rating: 4.9,
        reviewCount: 390,
      },
    ],
    doctors: 18,
    facilities: [
      'Digital X-ray & CBCT',
      'Laser dentistry suite',
      'In-house lab',
      'Patient lounge',
      'Airport pickup available',
    ],
    nearbyStays: [
      { name: 'The Ritz-Carlton', distance: '15 min' },
      { name: 'JW Marriott', distance: '20 min' },
      { name: 'Taj MG Road', distance: '10 min' },
    ],
    fromAirport: '40 min from Kempegowda International Airport',
    coordinates: { lat: 12.9716, lng: 77.5946 },
    featured: true,
    opensInNewTab: true,
  },
  {
    id: 'chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    type: 'treatment',
    tagline: 'Healthcare excellence in South India',
    description: 'Chennai is renowned for medical tourism. Our center offers exceptional dental care with the warmth of South Indian hospitality.',
    clinics: [
      {
        name: 'Atidi Dental Care - Nungambakkam',
        address: 'Nungambakkam, Chennai 600034',
        phone: '+91 44 XXXX XXXX',
        specialties: ['Implants', 'Full Mouth', 'Orthodontics'],
        rating: 4.8,
        reviewCount: 320,
      },
    ],
    doctors: 15,
    facilities: [
      'Digital imaging suite',
      'Dental lab on-site',
      'Sterilization center',
      'Recovery rooms',
      'Airport pickup available',
    ],
    nearbyStays: [
      { name: 'ITC Grand Chola', distance: '15 min' },
      { name: 'The Leela Palace', distance: '20 min' },
      { name: 'Taj Coromandel', distance: '10 min' },
    ],
    fromAirport: '35 min from Chennai International Airport',
    coordinates: { lat: 13.0827, lng: 80.2707 },
    featured: true,
    opensInNewTab: true,
  },
  {
    id: 'vijayawada',
    city: 'Vijayawada',
    state: 'Andhra Pradesh',
    country: 'India',
    type: 'treatment',
    tagline: 'Quality dental care in the heart of Andhra',
    description: 'Our Vijayawada center provides accessible, affordable dental care with modern facilities and experienced specialists.',
    clinics: [
      {
        name: 'Atidi Dental Care - MG Road',
        address: 'MG Road, Vijayawada 520010',
        phone: '+91 866 XXXX XXXX',
        specialties: ['Implants', 'Root Canal', 'Cosmetic'],
        rating: 4.7,
        reviewCount: 280,
      },
    ],
    doctors: 12,
    facilities: [
      'Digital X-ray',
      'Dental lab on-site',
      'Sterilization center',
      'Patient lounge',
    ],
    nearbyStays: [
      { name: 'The Gateway Hotel', distance: '10 min' },
      { name: 'Novotel', distance: '15 min' },
    ],
    fromAirport: '25 min from Vijayawada International Airport',
    coordinates: { lat: 16.5062, lng: 80.6480 },
    featured: false,
    opensInNewTab: true,
  },
  {
    id: 'visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    country: 'India',
    type: 'treatment',
    tagline: 'Coastal excellence in dental care',
    description: 'Our Vizag center combines quality dental treatment with the beauty of India\'s jewel of the East Coast.',
    clinics: [
      {
        name: 'Atidi Dental Care - Beach Road',
        address: 'Beach Road, Visakhapatnam 530002',
        phone: '+91 891 XXXX XXXX',
        specialties: ['Implants', 'Cosmetic', 'Orthodontics'],
        rating: 4.8,
        reviewCount: 310,
      },
    ],
    doctors: 14,
    facilities: [
      'Digital X-ray & CBCT',
      'In-house lab',
      'Sterilization suite',
      'Recovery rooms',
    ],
    nearbyStays: [
      { name: 'Novotel Varun Beach', distance: '5 min' },
      { name: 'The Park', distance: '10 min' },
    ],
    fromAirport: '20 min from Visakhapatnam Airport',
    coordinates: { lat: 17.6868, lng: 83.2185 },
    featured: false,
    opensInNewTab: true,
  },
  {
    id: 'tirupati',
    city: 'Tirupati',
    state: 'Andhra Pradesh',
    country: 'India',
    type: 'treatment',
    tagline: 'Sacred city, modern dental care',
    description: 'Combine your spiritual journey with quality dental treatment at our Tirupati center.',
    clinics: [
      {
        name: 'Atidi Dental Care - Tirumala Road',
        address: 'Tirumala Road, Tirupati 517501',
        phone: '+91 877 XXXX XXXX',
        specialties: ['Root Canal', 'Implants', 'General Dentistry'],
        rating: 4.7,
        reviewCount: 220,
      },
    ],
    doctors: 8,
    facilities: [
      'Digital X-ray',
      'Sterilization center',
      'Patient lounge',
    ],
    nearbyStays: [
      { name: 'Fortune Select Grand Ridge', distance: '10 min' },
      { name: 'Marasa Sarovar Premiere', distance: '15 min' },
    ],
    fromAirport: '15 min from Tirupati Airport',
    coordinates: { lat: 13.6288, lng: 79.4192 },
    featured: false,
    opensInNewTab: true,
  },
  {
    id: 'warangal',
    city: 'Warangal',
    state: 'Telangana',
    country: 'India',
    type: 'treatment',
    tagline: 'Heritage city with modern dental solutions',
    description: 'Our Warangal center brings quality dental care to the historic Kakatiya region.',
    clinics: [
      {
        name: 'Atidi Dental Care - Hanamkonda',
        address: 'Hanamkonda, Warangal 506001',
        phone: '+91 870 XXXX XXXX',
        specialties: ['Root Canal', 'Cosmetic', 'General Dentistry'],
        rating: 4.6,
        reviewCount: 180,
      },
    ],
    doctors: 6,
    facilities: [
      'Digital X-ray',
      'Sterilization center',
      'Patient comfort amenities',
    ],
    nearbyStays: [
      { name: 'Hotel Ashoka', distance: '5 min' },
      { name: 'Haritha Hotel', distance: '10 min' },
    ],
    fromAirport: '150 km from Hyderabad Airport',
    coordinates: { lat: 17.9784, lng: 79.5941 },
    featured: false,
    opensInNewTab: true,
  },
  {
    id: 'karimnagar',
    city: 'Karimnagar',
    state: 'Telangana',
    country: 'India',
    type: 'treatment',
    tagline: 'Trusted dental care in northern Telangana',
    description: 'Our Karimnagar center provides quality dental services to the northern Telangana region.',
    clinics: [
      {
        name: 'Atidi Dental Care - Mankammathota',
        address: 'Mankammathota, Karimnagar 505001',
        phone: '+91 878 XXXX XXXX',
        specialties: ['Root Canal', 'Implants', 'General Dentistry'],
        rating: 4.6,
        reviewCount: 140,
      },
    ],
    doctors: 5,
    facilities: [
      'Digital X-ray',
      'Sterilization center',
      'Patient comfort',
    ],
    nearbyStays: [
      { name: 'Hotel Karimnagar Grand', distance: '5 min' },
    ],
    fromAirport: '165 km from Hyderabad Airport',
    coordinates: { lat: 18.4386, lng: 79.1288 },
    featured: false,
    opensInNewTab: true,
  },
  {
    id: 'nizamabad',
    city: 'Nizamabad',
    state: 'Telangana',
    country: 'India',
    type: 'treatment',
    tagline: 'Quality dental solutions in Nizamabad',
    description: 'Our Nizamabad center brings modern dental care to the heart of Telangana.',
    clinics: [
      {
        name: 'Atidi Dental Care - Main Road',
        address: 'Main Road, Nizamabad 503001',
        phone: '+91 846 XXXX XXXX',
        specialties: ['Root Canal', 'Cosmetic', 'General Dentistry'],
        rating: 4.5,
        reviewCount: 120,
      },
    ],
    doctors: 4,
    facilities: [
      'Digital X-ray',
      'Sterilization center',
      'Patient comfort',
    ],
    nearbyStays: [
      { name: 'Hotel Haritha', distance: '5 min' },
    ],
    fromAirport: '150 km from Hyderabad Airport',
    coordinates: { lat: 18.6725, lng: 78.0940 },
    featured: false,
    opensInNewTab: true,
  },
  {
    id: 'guntur',
    city: 'Guntur',
    state: 'Andhra Pradesh',
    country: 'India',
    type: 'treatment',
    tagline: 'Trusted dental care in Guntur',
    description: 'Our Guntur center provides quality dental services to the thriving agricultural hub of Andhra Pradesh.',
    clinics: [
      {
        name: 'Atidi Dental Care - Brodipet',
        address: 'Brodipet, Guntur 522002',
        phone: '+91 863 XXXX XXXX',
        specialties: ['Root Canal', 'Implants', 'General Dentistry'],
        rating: 4.6,
        reviewCount: 190,
      },
    ],
    doctors: 7,
    facilities: [
      'Digital X-ray',
      'Sterilization center',
      'Patient amenities',
    ],
    nearbyStays: [
      { name: 'Hotel Vijaya International', distance: '5 min' },
      { name: 'Gateway Hotel', distance: '10 min' },
    ],
    fromAirport: '35 min from Vijayawada Airport',
    coordinates: { lat: 16.3067, lng: 80.4365 },
    featured: false,
    opensInNewTab: true,
  },
  {
    id: 'nellore',
    city: 'Nellore',
    state: 'Andhra Pradesh',
    country: 'India',
    type: 'treatment',
    tagline: 'Quality dental care in coastal Andhra',
    description: 'Our Nellore center serves the coastal region with modern dental facilities and experienced staff.',
    clinics: [
      {
        name: 'Atidi Dental Care - Grand Trunk Road',
        address: 'Grand Trunk Road, Nellore 524001',
        phone: '+91 861 XXXX XXXX',
        specialties: ['Root Canal', 'Cosmetic', 'General Dentistry'],
        rating: 4.5,
        reviewCount: 150,
      },
    ],
    doctors: 5,
    facilities: [
      'Digital X-ray',
      'Sterilization center',
      'Patient comfort',
    ],
    nearbyStays: [
      { name: 'Hotel Minerva Grand', distance: '5 min' },
    ],
    fromAirport: '160 km from Chennai Airport',
    coordinates: { lat: 14.4426, lng: 79.9865 },
    featured: false,
    opensInNewTab: true,
  },
  {
    id: 'vijayanagaram',
    city: 'Vijayanagaram',
    state: 'Andhra Pradesh',
    country: 'India',
    type: 'treatment',
    tagline: 'Fort city dental excellence',
    description: 'Our Vijayanagaram center provides quality dental care in this historic fort city of North Andhra.',
    clinics: [
      {
        name: 'Atidi Dental Care - Main Road',
        address: 'Main Road, Vijayanagaram 535002',
        phone: '+91 896 XXXX XXXX',
        specialties: ['Root Canal', 'Implants', 'General Dentistry'],
        rating: 4.5,
        reviewCount: 110,
      },
    ],
    doctors: 4,
    facilities: [
      'Digital X-ray',
      'Sterilization center',
      'Patient comfort',
    ],
    nearbyStays: [
      { name: 'Hotel Grand Palace', distance: '5 min' },
    ],
    fromAirport: '55 km from Visakhapatnam Airport',
    coordinates: { lat: 18.1067, lng: 83.3956 },
    featured: false,
    opensInNewTab: true,
  },
  {
    id: 'kakinada',
    city: 'Kakinada',
    state: 'Andhra Pradesh',
    country: 'India',
    type: 'treatment',
    tagline: 'Coastal Andhra dental care hub',
    description: 'Our Kakinada center serves the coastal Godavari region with modern dental facilities.',
    clinics: [
      {
        name: 'Atidi Dental Care - Main Road',
        address: 'Main Road, Kakinada 533001',
        phone: '+91 884 XXXX XXXX',
        specialties: ['Root Canal', 'Cosmetic', 'General Dentistry'],
        rating: 4.6,
        reviewCount: 130,
      },
    ],
    doctors: 5,
    facilities: [
      'Digital X-ray',
      'Sterilization center',
      'Patient amenities',
    ],
    nearbyStays: [
      { name: 'Hotel Kakinada Grand', distance: '5 min' },
    ],
    fromAirport: '60 km from Rajahmundry Airport',
    coordinates: { lat: 16.9891, lng: 82.2475 },
    featured: false,
    opensInNewTab: true,
  },
  {
    id: 'rajamandry',
    city: 'Rajamandry',
    state: 'Andhra Pradesh',
    country: 'India',
    type: 'treatment',
    tagline: 'Cultural capital dental care',
    description: 'Our Rajamandry center offers quality dental treatment in the cultural capital of Andhra Pradesh.',
    clinics: [
      {
        name: 'Atidi Dental Care - Main Road',
        address: 'Main Road, Rajahmundry 533101',
        phone: '+91 883 XXXX XXXX',
        specialties: ['Root Canal', 'Implants', 'General Dentistry'],
        rating: 4.6,
        reviewCount: 150,
      },
    ],
    doctors: 6,
    facilities: [
      'Digital X-ray',
      'Sterilization center',
      'Patient comfort',
    ],
    nearbyStays: [
      { name: 'Hotel Anand Regency', distance: '5 min' },
    ],
    fromAirport: '10 min from Rajahmundry Airport',
    coordinates: { lat: 17.0005, lng: 81.8040 },
    featured: false,
    opensInNewTab: true,
  },
  {
    id: 'bheemavaram',
    city: 'Bheemavaram',
    state: 'Andhra Pradesh',
    country: 'India',
    type: 'treatment',
    tagline: 'West Godavari dental solutions',
    description: 'Our Bheemavaram center brings modern dental care to the West Godavari district.',
    clinics: [
      {
        name: 'Atidi Dental Care - Main Road',
        address: 'Main Road, Bhimavaram 534201',
        phone: '+91 816 XXXX XXXX',
        specialties: ['Root Canal', 'Cosmetic', 'General Dentistry'],
        rating: 4.5,
        reviewCount: 100,
      },
    ],
    doctors: 4,
    facilities: [
      'Digital X-ray',
      'Sterilization center',
      'Patient comfort',
    ],
    nearbyStays: [
      { name: 'Hotel Bhimavaram Grand', distance: '5 min' },
    ],
    fromAirport: '90 km from Vijayawada Airport',
    coordinates: { lat: 16.5449, lng: 81.5212 },
    featured: false,
    opensInNewTab: true,
  },
  {
    id: 'eluru',
    city: 'Eluru',
    state: 'Andhra Pradesh',
    country: 'India',
    type: 'treatment',
    tagline: 'Trusted dental care in Eluru',
    description: 'Our Eluru center provides accessible dental care in the heart of West Godavari.',
    clinics: [
      {
        name: 'Atidi Dental Care - Main Road',
        address: 'Main Road, Eluru 534001',
        phone: '+91 883 XXXX XXXX',
        specialties: ['Root Canal', 'Implants', 'General Dentistry'],
        rating: 4.5,
        reviewCount: 95,
      },
    ],
    doctors: 4,
    facilities: [
      'Digital X-ray',
      'Sterilization center',
      'Patient comfort',
    ],
    nearbyStays: [
      { name: 'Hotel Eluru Grand', distance: '5 min' },
    ],
    fromAirport: '60 km from Vijayawada Airport',
    coordinates: { lat: 16.7107, lng: 81.0952 },
    featured: false,
    opensInNewTab: true,
  },
  {
    id: 'ongole',
    city: 'Ongole',
    state: 'Andhra Pradesh',
    country: 'India',
    type: 'treatment',
    tagline: 'Quality dental care in Prakasam district',
    description: 'Our Ongole center serves the Prakasam region with modern dental facilities.',
    clinics: [
      {
        name: 'Atidi Dental Care - Kurnool Road',
        address: 'Kurnool Road, Ongole 523001',
        phone: '+91 859 XXXX XXXX',
        specialties: ['Root Canal', 'Cosmetic', 'General Dentistry'],
        rating: 4.5,
        reviewCount: 105,
      },
    ],
    doctors: 4,
    facilities: [
      'Digital X-ray',
      'Sterilization center',
      'Patient comfort',
    ],
    nearbyStays: [
      { name: 'Hotel Ongole Grand', distance: '5 min' },
    ],
    fromAirport: '250 km from Vijayawada Airport',
    coordinates: { lat: 15.5057, lng: 80.0499 },
    featured: false,
    opensInNewTab: true,
  },
  {
    id: 'chittoor',
    city: 'Chittoor',
    state: 'Andhra Pradesh',
    country: 'India',
    type: 'treatment',
    tagline: 'Mango city dental care',
    description: 'Our Chittoor center provides dental services at the gateway to Tirupati.',
    clinics: [
      {
        name: 'Atidi Dental Care - Main Road',
        address: 'Main Road, Chittoor 517001',
        phone: '+91 857 XXXX XXXX',
        specialties: ['Root Canal', 'Implants', 'General Dentistry'],
        rating: 4.5,
        reviewCount: 90,
      },
    ],
    doctors: 4,
    facilities: [
      'Digital X-ray',
      'Sterilization center',
      'Patient comfort',
    ],
    nearbyStays: [
      { name: 'Hotel Chittoor Grand', distance: '5 min' },
    ],
    fromAirport: '70 km from Tirupati Airport',
    coordinates: { lat: 13.2172, lng: 79.1003 },
    featured: false,
    opensInNewTab: true,
  },
  {
    id: 'anantapur',
    city: 'Anantapur',
    state: 'Andhra Pradesh',
    country: 'India',
    type: 'treatment',
    tagline: 'Reliable dental care in Rayalaseema',
    description: 'Our Anantapur center brings quality dental services to the Rayalaseema region.',
    clinics: [
      {
        name: 'Atidi Dental Care - Main Road',
        address: 'Main Road, Anantapur 515001',
        phone: '+91 855 XXXX XXXX',
        specialties: ['Root Canal', 'Cosmetic', 'General Dentistry'],
        rating: 4.5,
        reviewCount: 85,
      },
    ],
    doctors: 4,
    facilities: [
      'Digital X-ray',
      'Sterilization center',
      'Patient comfort',
    ],
    nearbyStays: [
      { name: 'Hotel Royal Inn', distance: '5 min' },
    ],
    fromAirport: '140 km from Kurnool Airport',
    coordinates: { lat: 14.6819, lng: 77.6006 },
    featured: false,
    opensInNewTab: true,
  },
  {
    id: 'kurnool',
    city: 'Kurnool',
    state: 'Andhra Pradesh',
    country: 'India',
    type: 'treatment',
    tagline: 'Gateway of Rayalaseema dental hub',
    description: 'Our Kurnool center offers dental care in the judicial capital region of Andhra Pradesh.',
    clinics: [
      {
        name: 'Atidi Dental Care - Main Road',
        address: 'Main Road, Kurnool 518001',
        phone: '+91 851 XXXX XXXX',
        specialties: ['Root Canal', 'Implants', 'General Dentistry'],
        rating: 4.5,
        reviewCount: 100,
      },
    ],
    doctors: 5,
    facilities: [
      'Digital X-ray',
      'Sterilization center',
      'Patient comfort',
    ],
    nearbyStays: [
      { name: 'Hotel Kurnool Grand', distance: '5 min' },
    ],
    fromAirport: '10 min from Kurnool Airport',
    coordinates: { lat: 15.8281, lng: 78.0373 },
    featured: false,
    opensInNewTab: true,
  },
  {
    id: 'kadapa',
    city: 'Kadapa',
    state: 'Andhra Pradesh',
    country: 'India',
    type: 'treatment',
    tagline: 'Quality dental care in Kadapa',
    description: 'Our Kadapa center provides modern dental services in the heart of Rayalaseema.',
    clinics: [
      {
        name: 'Atidi Dental Care - Main Road',
        address: 'Main Road, Kadapa 516001',
        phone: '+91 856 XXXX XXXX',
        specialties: ['Root Canal', 'Cosmetic', 'General Dentistry'],
        rating: 4.5,
        reviewCount: 95,
      },
    ],
    doctors: 4,
    facilities: [
      'Digital X-ray',
      'Sterilization center',
      'Patient comfort',
    ],
    nearbyStays: [
      { name: 'Hotel Kadapa Grand', distance: '5 min' },
    ],
    fromAirport: '140 km from Tirupati Airport',
    coordinates: { lat: 14.4674, lng: 78.8241 },
    featured: false,
    opensInNewTab: true,
  },
  {
    id: 'madurai',
    city: 'Madurai',
    state: 'Tamil Nadu',
    country: 'India',
    type: 'treatment',
    tagline: 'Temple city with modern dental care',
    description: 'Our Madurai center offers quality dental care in one of Tamil Nadu\'s most historic and culturally rich cities.',
    clinics: [
      {
        name: 'Atidi Dental Care - Anna Nagar',
        address: 'Anna Nagar, Madurai 625020',
        phone: '+91 452 XXXX XXXX',
        specialties: ['Implants', 'Root Canal', 'General Dentistry'],
        rating: 4.7,
        reviewCount: 210,
      },
    ],
    doctors: 9,
    facilities: [
      'Digital X-ray',
      'In-house lab',
      'Sterilization suite',
    ],
    nearbyStays: [
      { name: 'Heritage Madurai', distance: '10 min' },
      { name: 'GRT Regency', distance: '15 min' },
    ],
    fromAirport: '15 min from Madurai Airport',
    coordinates: { lat: 9.9252, lng: 78.1198 },
    featured: false,
    opensInNewTab: true,
  },
  {
    id: 'coimbatore',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    country: 'India',
    type: 'treatment',
    tagline: 'Manchester of South India dental excellence',
    description: 'Our Coimbatore center offers comprehensive dental care in Tamil Nadu\'s industrial and educational hub.',
    clinics: [
      {
        name: 'Atidi Dental Care - RS Puram',
        address: 'RS Puram, Coimbatore 641002',
        phone: '+91 422 XXXX XXXX',
        specialties: ['Implants', 'Cosmetic', 'Orthodontics'],
        rating: 4.8,
        reviewCount: 340,
      },
    ],
    doctors: 12,
    facilities: [
      'Digital X-ray & CBCT',
      'In-house lab',
      'Sterilization suite',
      'Patient lounge',
    ],
    nearbyStays: [
      { name: 'Vivanta Coimbatore', distance: '10 min' },
      { name: 'Le Meridien', distance: '15 min' },
    ],
    fromAirport: '15 min from Coimbatore International Airport',
    coordinates: { lat: 11.0168, lng: 76.9558 },
    featured: false,
    opensInNewTab: true,
  },
]

export const usLocationsData: USLocationSeedData[] = [
  {
    id: 'new-jersey',
    city: 'New Jersey',
    state: 'New Jersey',
    stateCode: 'NJ',
    country: 'USA',
    type: 'followup',
    tagline: 'Follow-up care across the Garden State',
    description: 'Seamless follow-up care for patients returning from India. Emergency appointments guaranteed within 24 hours.',
    services: [
      'Post-treatment checkups',
      'Adjustment appointments',
      'Emergency care',
      'Minor corrections (free)',
      'Records transfer',
    ],
    guarantee: '24-hour appointment guarantee',
    emergencyLine: '+91 90309 91859',
    coordinates: { lat: 40.0583, lng: -74.4057 },
    featured: true,
    opensInNewTab: true,
  },
  {
    id: 'new-york',
    city: 'New York',
    state: 'New York',
    stateCode: 'NY',
    country: 'USA',
    type: 'followup',
    tagline: 'Follow-up care in the Empire State',
    description: 'Seamless follow-up care for patients returning from India. Emergency appointments guaranteed within 24 hours.',
    services: [
      'Post-treatment checkups',
      'Adjustment appointments',
      'Emergency care',
      'Minor corrections (free)',
      'Records transfer',
    ],
    guarantee: '24-hour appointment guarantee',
    emergencyLine: '+91 90309 91859',
    coordinates: { lat: 40.7128, lng: -74.0060 },
    featured: true,
    opensInNewTab: true,
  },
  {
    id: 'pennsylvania',
    city: 'Pennsylvania',
    state: 'Pennsylvania',
    stateCode: 'PA',
    country: 'USA',
    type: 'followup',
    tagline: 'Follow-up care in the Keystone State',
    description: 'Seamless follow-up care for patients returning from India. Emergency appointments guaranteed within 24 hours.',
    services: [
      'Post-treatment checkups',
      'Adjustment appointments',
      'Emergency care',
      'Minor corrections (free)',
      'Records transfer',
    ],
    guarantee: '24-hour appointment guarantee',
    emergencyLine: '+91 90309 91859',
    coordinates: { lat: 41.2033, lng: -77.1945 },
    featured: true,
    opensInNewTab: true,
  },
  {
    id: 'tennessee',
    city: 'Tennessee',
    state: 'Tennessee',
    stateCode: 'TN',
    country: 'USA',
    type: 'followup',
    tagline: 'Follow-up care in the Volunteer State',
    description: 'Seamless follow-up care for patients returning from India. Emergency appointments guaranteed within 24 hours.',
    services: [
      'Post-treatment checkups',
      'Adjustment appointments',
      'Emergency care',
      'Minor corrections (free)',
      'Records transfer',
    ],
    guarantee: '24-hour appointment guarantee',
    emergencyLine: '+91 90309 91859',
    coordinates: { lat: 35.5175, lng: -86.5804 },
    featured: true,
    opensInNewTab: true,
  },
  {
    id: 'virginia',
    city: 'Virginia',
    state: 'Virginia',
    stateCode: 'VA',
    country: 'USA',
    type: 'followup',
    tagline: 'Follow-up care in the Old Dominion',
    description: 'Seamless follow-up care for patients returning from India. Emergency appointments guaranteed within 24 hours.',
    services: [
      'Post-treatment checkups',
      'Adjustment appointments',
      'Emergency care',
      'Minor corrections (free)',
      'Records transfer',
    ],
    guarantee: '24-hour appointment guarantee',
    emergencyLine: '+91 90309 91859',
    coordinates: { lat: 37.4316, lng: -78.6569 },
    featured: true,
    opensInNewTab: true,
  },
  {
    id: 'connecticut',
    city: 'Connecticut',
    state: 'Connecticut',
    stateCode: 'CT',
    country: 'USA',
    type: 'followup',
    tagline: 'Follow-up care in the Constitution State',
    description: 'Seamless follow-up care for patients returning from India. Emergency appointments guaranteed within 24 hours.',
    services: [
      'Post-treatment checkups',
      'Adjustment appointments',
      'Emergency care',
      'Minor corrections (free)',
      'Records transfer',
    ],
    guarantee: '24-hour appointment guarantee',
    emergencyLine: '+91 90309 91859',
    coordinates: { lat: 41.6032, lng: -73.0877 },
    featured: true,
    opensInNewTab: true,
  },
  {
    id: 'massachusetts',
    city: 'Massachusetts',
    state: 'Massachusetts',
    stateCode: 'MA',
    country: 'USA',
    type: 'followup',
    tagline: 'Follow-up care in the Bay State',
    description: 'Seamless follow-up care for patients returning from India. Emergency appointments guaranteed within 24 hours.',
    services: [
      'Post-treatment checkups',
      'Adjustment appointments',
      'Emergency care',
      'Minor corrections (free)',
      'Records transfer',
    ],
    guarantee: '24-hour appointment guarantee',
    emergencyLine: '+91 90309 91859',
    coordinates: { lat: 42.4072, lng: -71.3824 },
    featured: true,
    opensInNewTab: true,
  },
  {
    id: 'maryland',
    city: 'Maryland',
    state: 'Maryland',
    stateCode: 'MD',
    country: 'USA',
    type: 'followup',
    tagline: 'Follow-up care in the Old Line State',
    description: 'Seamless follow-up care for patients returning from India. Emergency appointments guaranteed within 24 hours.',
    services: [
      'Post-treatment checkups',
      'Adjustment appointments',
      'Emergency care',
      'Minor corrections (free)',
      'Records transfer',
    ],
    guarantee: '24-hour appointment guarantee',
    emergencyLine: '+91 90309 91859',
    coordinates: { lat: 39.0458, lng: -76.6413 },
    featured: true,
    opensInNewTab: true,
  },
  {
    id: 'north-carolina',
    city: 'North Carolina',
    state: 'North Carolina',
    stateCode: 'NC',
    country: 'USA',
    type: 'followup',
    tagline: 'Follow-up care in the Tar Heel State',
    description: 'Seamless follow-up care for patients returning from India. Emergency appointments guaranteed within 24 hours.',
    services: [
      'Post-treatment checkups',
      'Adjustment appointments',
      'Emergency care',
      'Minor corrections (free)',
      'Records transfer',
    ],
    guarantee: '24-hour appointment guarantee',
    emergencyLine: '+91 90309 91859',
    coordinates: { lat: 35.7596, lng: -79.0193 },
    featured: true,
    opensInNewTab: true,
  },
  {
    id: 'texas',
    city: 'Texas',
    state: 'Texas',
    stateCode: 'TX',
    country: 'USA',
    type: 'followup',
    tagline: 'Follow-up care across the Lone Star State',
    description: 'Seamless follow-up care for patients returning from India. Emergency appointments guaranteed within 24 hours.',
    services: [
      'Post-treatment checkups',
      'Adjustment appointments',
      'Emergency care',
      'Minor corrections (free)',
      'Records transfer',
    ],
    guarantee: '24-hour appointment guarantee',
    emergencyLine: '+91 90309 91859',
    coordinates: { lat: 31.9686, lng: -99.9018 },
    featured: true,
    opensInNewTab: true,
  },
]
